//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; } = "RaoufSpecialWaffel";
        public Nullable<int> SupplierID { get; set; } = 1;
        public Nullable<int> CategoryID { get; set; } = 1;
        public string QuantityPerUnit { get; set; } = "20";
        public Nullable<decimal> UnitPrice { get; set; } = 0;
        public Nullable<short> UnitsInStock { get; set; } = 0;
        public Nullable<short> UnitsOnOrder { get; set; } = 0;
        public Nullable<short> ReorderLevel { get; set; } = 0;
        public bool Discontinued { get; set; } = false;

        public virtual Supplier Supplier { get; set; }
    }
}
