// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using NorthWind_WinApp.Models;

namespace NorthWind_WinApp.Context;

public partial class pubsContext : DbContext
{
    public pubsContext()
    {
    }

    public pubsContext(DbContextOptions<pubsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Publisher> Publishers { get; set; }

    public virtual DbSet<Title> Titles { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=pubs;Integrated Security=True; Encrypt=false");


    // fluent API
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Publisher>(entity =>
        {
            entity.HasKey(e => e.PubId).HasName("UPKCL_pubind");

            entity.Property(e => e.PubId).IsFixedLength();
            entity.Property(e => e.Country).HasDefaultValueSql("('USA')");
            entity.Property(e => e.State).IsFixedLength();
        });

        modelBuilder.Entity<Title>(entity =>
        {
            entity.HasKey(e => e.TitleId).HasName("UPKCL_titleidind");

            entity.Property(e => e.PubId).IsFixedLength();
            entity.Property(e => e.Pubdate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Type)
                .HasDefaultValueSql("('UNDECIDED')")
                .IsFixedLength();

            entity.HasOne(d => d.Pub).WithMany(p => p.Titles)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK__titles__pub_id__1A14E395");
        });

        OnModelCreatingPartial(modelBuilder);
    }


    // Partial method, not used if another class doesn't implement it.

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}